server:
  port: 8080

spring:
  application:
    name: api-gateway
  security:
    user:
      name: disabled
      password: disabled
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: identity-service-auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader
        - id: identity-service-users
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/users/**
          filters:
            - PreserveHostHeader
        - id: identity-service-users-exact
          uri: http://localhost:8081
          predicates:
            - Path=/api/admin/users
          filters:
            - PreserveHostHeader
        - id: admin-service-brands
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/brands/**
          filters:
            - PreserveHostHeader
        - id: admin-service-categories
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/categories/**
          filters:
            - PreserveHostHeader
        - id: admin-service-marketplaces
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/marketplaces/**
          filters:
            - PreserveHostHeader
        - id: admin-service-custom-fields
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/custom-fields/**
          filters:
            - PreserveHostHeader
        - id: admin-service-attributes
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/attributes/**
          filters:
            - PreserveHostHeader
        - id: admin-service-products
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/products/**
          filters:
            - PreserveHostHeader
        - id: product-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/products/**
          filters:
            - PreserveHostHeader
        - id: pricing-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/pricing/**
          filters:
            - PreserveHostHeader
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
