server:
  port: 8081

spring:
  application:
    name: identity-service
  security:
    user:
      name: disabled  
      password: disabled
  datasource:
    url: jdbc:mysql://localhost:3306/identity_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Adarsh@.27

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:mySecretKeyForDevelopmentOnlyChangeInProduction}
  expiration: 14400000 # 4 hours in milliseconds

logging:
  level:
    com.elowen.identity: DEBUG
